[[news]]
date = "2025"
content = "MIRRIFT and FRIM were published in IEEE Transactions on Geoscience and Remote Sensing as first-author research."

[[news]]
date = "2023"
content = "Started PhD study at Wuhan University in the State Key Laboratory of Information Engineering in Surveying, Mapping and Remote Sensing."
